GOODREAD_QUOTE_TAG_WITH_URLS = {
            "Default":"https://www.goodreads.com/quotes/tag/quotes",
            "Faith":"https://www.goodreads.com/quotes/tag/faith",
            "God":"https://www.goodreads.com/quotes/tag/god",
            "Happiness":"https://www.goodreads.com/quotes/tag/happiness",
            "Hope":"https://www.goodreads.com/quotes/tag/hope",
            "Humor":"https://www.goodreads.com/quotes/tag/humor",
            "Inspiration":"https://www.goodreads.com/quotes/tag/inspiration",
            "Inspirational":"https://www.goodreads.com/quotes/tag/inspirational-quotes",
            "Life":"https://www.goodreads.com/quotes/tag/life-quotes",
            "Life Lessons":"https://www.goodreads.com/quotes/tag/life-lessons",
            "Love":"https://www.goodreads.com/quotes/tag/love-quotes",
            "Motivation":"https://www.goodreads.com/quotes/tag/motivation",
            "Motivational":"https://www.goodreads.com/quotes/tag/motivational-quotes",
            "Philosophy":"https://www.goodreads.com/quotes/tag/philosophy",
            "Poetry":"https://www.goodreads.com/quotes/tag/poetry",
            "Relationships":"https://www.goodreads.com/quotes/tag/relationships",
            "Religion":"https://www.goodreads.com/quotes/tag/religion",
            "Romance":"https://www.goodreads.com/quotes/tag/romance",
            "Science":"https://www.goodreads.com/quotes/tag/science",
            "Spirituality":"https://www.goodreads.com/quotes/tag/spirituality",
            "Success":"https://www.goodreads.com/quotes/tag/success",
            "Time":"https://www.goodreads.com/quotes/tag/time",
            "Truth":"https://www.goodreads.com/quotes/tag/truth",
            "Wisdom":"https://www.goodreads.com/quotes/tag/wisdom",
            "Writing":"https://www.goodreads.com/quotes/tag/writing",
        }